
###
GET http://localhost:3000/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY5ODg5MTksImV4cCI6MTY0NzAzMjExOSwiYXVkIjoiNjIyYjBkZWI5ZGViMmFlZDEzZGMwMDMyIiwiaXNzIjoiZS13YWxsZXQuY29tIn0.iImXhRIW5MZWCOlBQdcqaYfCkzKfCJcNLf83VIqcc9k

### signup
POST http://localhost:3000/auth/signup
Content-Type:application/json


{
    "username":"SohamBiswas4",
    "password":"12346"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username":"SohamBiswas4",
    "password":"12346"
}

###refresh-token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY5Nzg2NzYsImV4cCI6MTY0NzAyMTg3NiwiYXVkIjoiNjIyODdlYmYxYzZlNDlhN2ZhOGExN2ZjIiwiaXNzIjoiZS13YWxsZXQuY29tIn0.j8TVllL_l-XSdsneE91a67Kcfooa2l0HQMe6_EjA7AY"
}
###logut
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY5Nzk1MTgsImV4cCI6MTY3ODUzNzExOCwiYXVkIjoiNjIyODdlYmYxYzZlNDlhN2ZhOGExN2ZjIiwiaXNzIjoiZS13YWxsZXQuY29tIn0.GmyEDlHi7jWRaHio80mhEK5yH36AiBt_U00mZe026bI"
    
}