
###
GET http://localhost:3000/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDczMjQ4ODYsImV4cCI6MTY0NzM2ODA4NiwiYXVkIjoiNjIzMDJlY2QwYWNjMjdiNmUxMTg2ODE1IiwiaXNzIjoiZS13YWxsZXQuY29tIn0.w8YCZbY74vKlAXWUiQrqikWKcNfL7set_o5Ji9oa4zo
### signup
POST http://localhost:3000/auth/signup
Content-Type:application/json


{
    "firstname":"soham",
    "lastname":"biswas2",
    "password":"12345678",
    "phoneNumber":"6290883956"

    
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "accountnumber":10990005,
    "password":"12345678"
}

###refresh-token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY5Nzg2NzYsImV4cCI6MTY0NzAyMTg3NiwiYXVkIjoiNjIyODdlYmYxYzZlNDlhN2ZhOGExN2ZjIiwiaXNzIjoiZS13YWxsZXQuY29tIn0.j8TVllL_l-XSdsneE91a67Kcfooa2l0HQMe6_EjA7AY"
}
###logut
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY5Nzk1MTgsImV4cCI6MTY3ODUzNzExOCwiYXVkIjoiNjIyODdlYmYxYzZlNDlhN2ZhOGExN2ZjIiwiaXNzIjoiZS13YWxsZXQuY29tIn0.GmyEDlHi7jWRaHio80mhEK5yH36AiBt_U00mZe026bI"
    
}